#ifndef SHARED_COLLISION_CONSTANTS_H
#define SHARED_COLLISION_CONSTANTS_H

#include <cstdint>

enum CollisionType : uint32_t {
  PLAYER_COLLISION_TYPE           = (1<<0),
  WALL_COLLISION_TYPE             = (1<<1),
  MONSTER_COLLISION_TYPE          = (1<<2),
  SMALL_DECORATION_COLLISION_TYPE = (1<<3),
  BIG_DECORATION_COLLISION_TYPE   = (1<<4),
  DOOR_COLLISION_TYPE             = (1<<5),
  INTERACTION_COLLISION_TYPE      = (1<<6),
  GHOST_COLLISION_TYPE            = (1<<7),
  NOCLIP_COLLISION_TYPE           = (1<<8),
  EVERYTHING                      = UINT32_MAX
};

const uint32_t player_collision_filter = PLAYER_COLLISION_TYPE | WALL_COLLISION_TYPE | MONSTER_COLLISION_TYPE | BIG_DECORATION_COLLISION_TYPE | DOOR_COLLISION_TYPE | INTERACTION_COLLISION_TYPE;
const uint32_t wall_collision_filter = PLAYER_COLLISION_TYPE | MONSTER_COLLISION_TYPE | INTERACTION_COLLISION_TYPE | GHOST_COLLISION_TYPE;
const uint32_t monster_collision_filter = PLAYER_COLLISION_TYPE | WALL_COLLISION_TYPE | MONSTER_COLLISION_TYPE | BIG_DECORATION_COLLISION_TYPE | DOOR_COLLISION_TYPE | INTERACTION_COLLISION_TYPE;
const uint32_t small_decoration_collision_filter = WALL_COLLISION_TYPE | BIG_DECORATION_COLLISION_TYPE | DOOR_COLLISION_TYPE | INTERACTION_COLLISION_TYPE;
const uint32_t big_decoration_collision_filter = PLAYER_COLLISION_TYPE | MONSTER_COLLISION_TYPE | WALL_COLLISION_TYPE | DOOR_COLLISION_TYPE | INTERACTION_COLLISION_TYPE;
const uint32_t interaction_collision_filter = PLAYER_COLLISION_TYPE | MONSTER_COLLISION_TYPE | WALL_COLLISION_TYPE | SMALL_DECORATION_COLLISION_TYPE | BIG_DECORATION_COLLISION_TYPE | DOOR_COLLISION_TYPE;
const uint32_t ghost_collision_filter = WALL_COLLISION_TYPE;
const uint32_t noclip_collision_filter = 0;

#endif
